AWSTemplateFormatVersion: '2010-09-09'
Description: ACFS3 - Certificate creation

Parameters:
  DomainName:
    Type: String
  SubDomain:
    Type: String
  HostedZoneId:
    Type: String

Resources:
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub '${SubDomain}.${DomainName}'
      DomainValidationOptions:
        - DomainName: !Sub '${SubDomain}.${DomainName}'
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

Outputs:
  CertificateArn:
    Description: Issued certificate
    Value: !Ref Certificate
