AWSTemplateFormatVersion: "2010-09-09"
Description: Resources needed to orchestrate the counters
Transform: AWS::Serverless-2016-10-31

Parameters:
  ResourcePrefix:
    Description: A prefix to be used for resource names, useful for separate testing
    Type: String
    Default: test-resume
    AllowedPattern: ^[a-zA-Z\-\_0-9]+$

Globals:
  Function:
    Runtime: python3.9
    CodeUri: ../app/
    Environment:
      Variables:
        QUEUE_NAME: !Sub '${ResourcePrefix}-incoming-request-queue'

Resources:
  IncomingRequestFunction:
    Type: AWS::Serverless::Function
    Name: !Sub '${ResourcePrefix}-lambda'
    Properties:
      Handler: app.lambda_incoming_to_sqs_handler
      Architectures:
        - x86_64
      Policies:
        SQSSendMessagePolicy:
          QueueName: !GetAtt IncomingRequestQueue.QueueName
      Environment:
        Variables:
          SITE_COUNTS: !Ref SiteCountTable
          TOTAL_COUNT: !Ref TotalCountTable
          IP_COUNTS: !Ref IpCountTable

  SiteCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: path
        Type: String
      TableName: !Sub '${ResourcePrefix}-PathCounts'
      Tags:
        project: resume-skiadas

  TotalCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: count
        Type: String
      TableName: !Sub '${ResourcePrefix}-TotalCount'
      Tags:
        project: resume-skiadas

  IpCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ip
        Type: String
      TableName: !Sub '${ResourcePrefix}-IpCounts'
      Tags:
        project: resume-skiadas


  IncomingRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ResourcePrefix}-incoming-request-queue'
      MessageRetentionPeriod: 3600 # One hour
      Tags:
        - Key: project
          Value: resume-skiadas

Outputs:
  IncomingRequestFunction:
    Description: Function to trigger on viewer requests
    Value: !GetAtt IncomingRequestFunction.Arn
    Export:
      Name: IncomingRequestFunctionArn
