AWSTemplateFormatVersion: "2010-09-09"
Description: Resources needed to orchestrate the counters
Transform: AWS::Serverless-2016-10-31

Resources:
  TotalCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: path
        Type: String
      TableName: skiadas-resume-SitePathCounts
      Tags:
        project: resume-skiadas

  IncomingRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: skiadas-resume-incoming-request-queue
      MessageRetentionPeriod: 3600 # One hour
      Tags:
        - Key: project
          Value: resume-skiadas
