AWSTemplateFormatVersion: "2010-09-09"
Description: Resources needed to orchestrate the counters
Transform: AWS::Serverless-2016-10-31

Parameters:
  ResourcePrefix:
    Description: A prefix to be used for resource names, useful for separate testing
    Type: String
    Default: test-resume
    AllowedPattern: ^[a-zA-Z\-\_0-9]+$

Globals:
  Function:
    Runtime: python3.9
    # The following should work but it doesn't. Known bug
    # CodeUri: ../app/src

Resources:
  QueueNameParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/skiadas/resume/counters/request_queue_name'
      Type: String
      Value: !Sub '${ResourcePrefix}-incoming-request-queue'
      Description: SSM Parameter for the queue name
  TotalsTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/skiadas/resume/counters/totals_table_name'
      Type: String
      Value: !Ref TotalCountTable
      Description: The name of the totals table
  PathsTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/skiadas/resume/counters/paths_table_name'
      Type: String
      Value: !Ref SiteCountTable
      Description: The name of the table holding paths counts
  IpCountTableParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/skiadas/resume/counters/ips_table_name'
      Type: String
      Value: !Ref IpCountTable
      Description: The name of the table holding ip counts

  IncomingRequestFunction:
    Type: AWS::Serverless::Function
    Name: !Sub '${ResourcePrefix}-lambda'
    Properties:
      CodeUri: ../app/src
      Handler: app.lambda_incoming_to_sqs_handler
      Architectures:
        - x86_64
      AutoPublishAlias: IncomingRequestFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - edgelambda.amazonaws.com
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt IncomingRequestQueue.QueueName
        - SSMParameterReadPolicy:
            ParameterName: 'skiadas/resume/counters/request_queue_name'

  SqsToDynamoDbFunction:
    Type: AWS::Serverless::Function
    Name: !Sub '${ResourcePrefix}-sqs-to-dynamodb'
    Properties:
      CodeUri: ../app/src
      Handler: app.lambda_processing_sqs_message
      Architectures:
        - x86_64
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt IncomingRequestQueue.QueueName
        - DynamoDBCrudPolicy:
            TableName: !Sub '${ResourcePrefix}-*'
      Events:
        NewSQSMessageEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt IncomingRequestQueue.Arn
            BatchSize: 1

  SiteCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: path
        Type: String
      Tags:
        project: resume-skiadas

  TotalCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: total
        Type: String
      Tags:
        project: resume-skiadas

  IpCountTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: ip
        Type: String
      Tags:
        project: resume-skiadas


  IncomingRequestQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub '${ResourcePrefix}-incoming-request-queue'
      MessageRetentionPeriod: 3600 # One hour
      Tags:
        - Key: project
          Value: resume-skiadas

Outputs:
  IncomingRequestFunctionVersion:
    Description: Function to trigger on viewer requests
    Value: !Ref IncomingRequestFunction.Version
