name: push-to-s3
on:
  push:
    paths:
      - "site/**"
      - "cloudFormation/**"
  workflow_dispatch:

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  pull-then-push:
    runs-on: ubuntu-latest
    env:
      ROLE: ${{ secrets.AWS_ROLE }}
      BUCKET: ${{ secrets.BUCKET_NAME }}
      SUBDOMAIN: ${{ secrets.SUBDOMAIN }}
      DOMAIN_NAME: ${{ secrets.DOMAIN }}
      ZONE_ID: ${{ secrets.HOSTED_ZONE_ID}}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Cloud Formation Linter with Latest Version
        uses: scottbrenner/cfn-lint-action@v2
      - name: Print the Cloud Formation Linter Version & run Linter.
        run: |
          cfn-lint --version
          cfn-lint -t ./cloudFormation/main.yaml
          cfn-lint -t ./cloudFormation/acm-certificate.yaml
          cfn-lint -t ./cloudFormation/buckets.yaml
          cfn-lint -t ./cloudFormation/cloudfront-site.yaml
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.ROLE }}
          role-duration-seconds: 900
          aws-region: us-east-1
      - run: >
          aws cloudformation package
          --template-file ./cloudFormation/main.yaml
          --s3-bucket skiadas-resume-templates
          --output-template-file packaged.template
      - run: >
          aws cloudformation deploy
          --stack-name skiadas-resume-stack
          --s3-bucket skiadas-resume-templates
          --template-file packaged.template
          --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND
          --disable-rollback
          --parameter-overrides SubDomain=$SUBDOMAIN DomainName=$DOMAIN_NAME
          HostedZoneId=$ZONE_ID BucketName=$BUCKET
      - run: aws s3 sync --delete ./site s3://$BUCKET
