name: push-to-s3
on: [push]
permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  pull-then-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::410438835476:role/github-actions-skiadas-resume
          role-duration-seconds: 900
          aws-region: us-east-1
      - run: aws s3 sync ./site s3://skiadas-resume
