name: push-to-s3
on:
  push:
    paths:
      - 'site/**'
      - 'cloudFormation/**'
  workflow_dispatch:

permissions:
  id-token: write # required to use OIDC authentication
  contents: read # required to checkout the code from the repo
jobs:
  pull-then-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          role-duration-seconds: 900
          aws-region: us-east-1
      - uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: skiadas-resume-stack
          template: ./cloudFormation/main.yaml
          parameter-overrides: "SubDomain=${{ secrets.SUBDOMAIN }},DomainName=${{ secrets.DOMAIN }},HostedZoneId=${{ secrets.HOSTED_ZONE_ID}},BucketName=${{ secrets.BUCKET_NAME}}"
      - run: aws s3 sync --delete ./site s3://${{ secrets.BUCKET_NAME }}

